/**
 * Canonical color tags used for products and room analysis.
 * Gemini output is normalized to these; product colorTags should use these values.
 */
export const CANONICAL_COLORS = [
  "white", "ivory", "cream", "grey", "black", "brown", "beige", "tan",
  "green", "sage", "mint", "olive", "teal", "blue", "navy", "red", "burgundy",
  "pink", "coral", "rose", "orange", "terracotta", "yellow", "gold", "mustard",
  "amber", "purple", "lavender", "brass", "copper", "bronze", "silver", "charcoal",
];

/**
 * Map from various color names (Gemini / UI) to canonical tag.
 */
export const COLOR_MAP = {
  white: "white",
  ivory: "ivory",
  cream: "cream",
  "off-white": "white",
  "off white": "white",
  grey: "grey",
  gray: "grey",
  silver: "silver",
  charcoal: "charcoal",
  black: "black",
  brown: "brown",
  wood: "brown",
  wooden: "brown",
  "light wood": "brown",
  "dark wood": "brown",
  walnut: "brown",
  oak: "brown",
  beige: "beige",
  tan: "tan",
  sand: "beige",
  green: "green",
  sage: "sage",
  mint: "mint",
  olive: "olive",
  forest: "green",
  emerald: "green",
  teal: "teal",
  turquoise: "teal",
  blue: "blue",
  navy: "navy",
  sky: "blue",
  red: "red",
  burgundy: "burgundy",
  maroon: "burgundy",
  crimson: "red",
  pink: "pink",
  coral: "coral",
  rose: "rose",
  blush: "pink",
  orange: "orange",
  terracotta: "terracotta",
  rust: "terracotta",
  yellow: "yellow",
  gold: "gold",
  brass: "brass",
  copper: "copper",
  bronze: "bronze",
  mustard: "mustard",
  amber: "amber",
  honey: "gold",
  purple: "purple",
  lavender: "lavender",
  violet: "purple",
  plum: "purple",
  lilac: "lavender",
};

/**
 * For each room accent color, these product color tags will look good
 * (complementary + analogous + neutrals). Used to score recommendations.
 */
export const COMPLEMENTARY_MAP = {
  white: ["black", "grey", "gold", "brass", "green", "blue", "terracotta", "navy", "brown", "charcoal"],
  ivory: ["grey", "gold", "sage", "terracotta", "brown", "navy", "black"],
  cream: ["brown", "sage", "navy", "terracotta", "gold", "grey", "black"],
  grey: ["gold", "coral", "teal", "mustard", "white", "black", "navy", "terracotta", "pink"],
  black: ["white", "gold", "brass", "grey", "red", "coral", "green"],
  brown: ["cream", "white", "sage", "green", "teal", "gold", "terracotta", "navy", "blue"],
  beige: ["sage", "navy", "terracotta", "brown", "green", "teal", "gold"],
  tan: ["navy", "white", "sage", "teal", "terracotta", "green"],
  green: ["white", "terracotta", "coral", "gold", "brown", "pink", "cream", "mustard"],
  sage: ["white", "terracotta", "cream", "brown", "gold", "navy", "terracotta", "coral"],
  mint: ["white", "gold", "coral", "grey", "terracotta", "navy"],
  olive: ["terracotta", "cream", "white", "gold", "mustard", "brown"],
  teal: ["coral", "gold", "white", "terracotta", "grey", "mustard", "cream"],
  blue: ["white", "gold", "terracotta", "orange", "cream", "grey", "mustard"],
  navy: ["white", "gold", "cream", "coral", "terracotta", "grey", "mustard", "brass"],
  red: ["white", "gold", "grey", "green", "navy", "black"],
  burgundy: ["gold", "grey", "white", "sage", "cream"],
  pink: ["green", "grey", "gold", "navy", "white", "sage"],
  coral: ["teal", "navy", "white", "grey", "sage", "mint", "gold"],
  rose: ["sage", "grey", "gold", "navy", "green"],
  orange: ["blue", "teal", "navy", "white", "grey"],
  terracotta: ["teal", "sage", "green", "white", "cream", "navy", "mint", "gold"],
  yellow: ["grey", "navy", "purple", "charcoal", "teal"],
  gold: ["navy", "green", "grey", "black", "burgundy", "white", "teal", "charcoal"],
  mustard: ["navy", "grey", "teal", "white", "burgundy", "charcoal"],
  amber: ["navy", "teal", "grey", "white"],
  purple: ["gold", "yellow", "grey", "white", "sage", "mint"],
  lavender: ["sage", "grey", "white", "gold", "terracotta", "navy"],
  brass: ["white", "navy", "green", "black", "grey"],
  copper: ["white", "teal", "sage", "navy", "grey"],
  bronze: ["white", "navy", "sage", "cream", "grey"],
  silver: ["white", "navy", "grey", "black", "coral", "teal"],
  charcoal: ["gold", "white", "coral", "mustard", "teal"],
};
